### ISSUE TITLE
TypeError: sequence item 0: expected str instance, bytes found

### ISSUE THREAD

**Issue by pando85** [beetbox/audioread#106]
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/audioread/ffdec.py", line 191, in read_data
    data = self.stdout_reader.queue.get(timeout=timeout)
  File "/usr/lib/python3.8/queue.py", line 178, in get
    raise Empty
_queue.Empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/beet", line 11, in <module>
    load_entry_point('beets==1.4.9', 'console_scripts', 'beet')()
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1266, in main
    _raw_main(args)
  File "/usr/lib/python3.8/site-packages/beets/ui/__init__.py", line 1253, in _raw_main
    subcommand.func(lib, suboptions, subargs)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 955, in import_func
    import_files(lib, paths, query)
  File "/usr/lib/python3.8/site-packages/beets/ui/commands.py", line 925, in import_files
    session.run()
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 329, in run
    pl.run_parallel(QUEUE_SIZE)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 445, in run_parallel
    six.reraise(exc_info[0], exc_info[1], exc_info[2])
  File "/usr/lib/python3.8/site-packages/six.py", line 703, in reraise
    raise value
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 312, in run
    out = self.coro.send(msg)
  File "/usr/lib/python3.8/site-packages/beets/util/pipeline.py", line 194, in coro
    func(*(args + (task,)))
  File "/usr/lib/python3.8/site-packages/beets/importer.py", line 1344, in lookup_candidates
    plugins.send('import_task_start', session=session, task=task)
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 489, in send
    result = handler(**arguments)
  File "/usr/lib/python3.8/site-packages/beets/plugins.py", line 143, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/beetsplug/chroma.py", line 182, in fingerprint_task
    return fingerprint_task(self._log, task, session)
  File "/usr/lib/python3.8/site-packages/beetsplug/chroma.py", line 251, in fingerprint_task
    acoustid_match(log, item.path)
  File "/usr/lib/python3.8/site-packages/beetsplug/chroma.py", line 91, in acoustid_match
    duration, fp = acoustid.fingerprint_file(util.syspath(path))
  File "/usr/lib/python3.8/site-packages/acoustid.py", line 324, in fingerprint_file
    return _fingerprint_file_audioread(path, maxlength)
  File "/usr/lib/python3.8/site-packages/acoustid.py", line 267, in _fingerprint_file_audioread
    fp = fingerprint(f.samplerate, f.channels, iter(f), maxlength)
  File "/usr/lib/python3.8/site-packages/acoustid.py", line 208, in fingerprint
    for block in pcmiter:
  File "/usr/lib/python3.8/site-packages/audioread/ffdec.py", line 205, in read_data
    ''.join(self.stderr_reader.queue.queue)
TypeError: sequence item 0: expected str instance, bytes found
```

Version:
```bash
# pip freeze | grep audioread
audioread==2.1.8
```

**Comment by sampsyo** [comment]
Hello! Any chance you could give a little more context about what exactly you were doing here? (Is this something we can reproduce?)

**Comment by pando85** [comment]
Na, I'm reading it correctly. It looks that is a timeout, sorry.

Thank you for your fast response. I was going to close it.

**Comment by sampsyo** [comment]
Cool. Nonetheless, our error handling code seems to have been wrong—I've pushed a fix that should make the exceptional path actually work correctly.
