### ISSUE TITLE
gstdec.FileReadError: gst_tag_demux_element_find

### ISSUE THREAD

**Issue by Serranya** [beetbox/audioread#143]
I have some wavpack files that cannot be fingerprinted by the chroma beets plugin. When I run

```python3
import audioread

audioread.available_backends()
audioread.gstdec.GstAudioFile(b'/serra-storage/Music/Battle Beast/2013 - Battle Beast/12. Black Ninja.wv')
```

I get the following error:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.11/site-packages/audioread/gstdec.py", line 248, in __init__
    raise self.read_exc
audioread.gstdec.FileReadError: ../gst-libs/gst/tag/gsttagdemux.c(1436): gst_tag_demux_element_find (): /GstPipeline:pipeline3/GstURIDecodeBin:uridecodebin3/GstDecodeBin:decodebin3/GstApeDemux:apedemux3
```

The file seems to be fine. Verifying it via wvunpack works as expected:
```
cloudbok:/serra-storage/Music/Battle Beast/2013 - Battle Beast$ wvunpack -v 12.\ Black\ Ninja.wv

 WVUNPACK  Hybrid Lossless Audio Decompressor  linux-musleabihf Version 5.7.0
 Copyright (c) 1998 - 2024 David Bryant.  All Rights Reserved.

verified 12. Black Ninja.wv in 19.16 secs (lossless, 25.96%
```

Most wavpack files work fine. Only some fail.

**Comment by Serranya** [comment]
I removed all the tags using `wvtag --clear` because I thought that maybe the metadata are corrupt. But the problem still remains.

**Comment by Serranya** [comment]
The error also occurs using gst-play:

```
cloudbok:~# gst-play-1.0 /serra-storage/Music/Battle\ Beast/2013\ -\ Battle\ Beast/12.\ Black\ Ninja.wv
Press 'k' to see a list of keyboard shortcuts.
Now playing /serra-storage/Music/Battle Beast/2013 - Battle Beast/12. Black Ninja.wv
ERROR Could not detect type of contents for file:///serra-storage/Music/Battle%20Beast/2013%20-%20Battle%20Beast/12.%20Black%20Ninja.wv
ERROR debug information: ../gst-libs/gst/tag/gsttagdemux.c(1436): gst_tag_demux_element_find (): /GstPlayBin:playbin/GstURIDecodeBin:uridecodebin0/GstDecodeBin:decodebin0/GstApeDemux:apedemux0
Reached end of play list.
```

I will create an upstream issue since audioread does not seem to be at fault here.

**Comment by Serranya** [comment]
Upstream issue created at https://gitlab.freedesktop.org/gstreamer/gstreamer/-/issues/3440
