### ISSUE TITLE
audioread + Bash on Windows

### ISSUE THREAD

**Issue by viggyfresh** [beetbox/audioread#51]
Hi there,

I was using `librosa` on my Windows machine via Bash on Windows and came across this error:

```
File "venv/local/lib/python2.7/site-packages/librosa/core/audio.py", line 144, in load
    y.append(frame)
  File "venv/local/lib/python2.7/site-packages/audioread/ffdec.py", line 279, in __exit__
    self.close()
  File "venv/local/lib/python2.7/site-packages/audioread/ffdec.py", line 263, in close
    self.proc.kill()
  File "/usr/lib/python2.7/subprocess.py", line 1572, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib/python2.7/subprocess.py", line 1562, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
Exception OSError: (3, 'No such process') in <bound method FFmpegAudioFile.__del__ of <audioread.ffdec.FFmpegAudioFile object at 0x7fcae7a492d0>>
 ignored
```

I think other folks with this (admittedly odd) usage pattern have seen similar issues as well (https://github.com/librosa/librosa/issues/536).

Any thoughts on this? Thanks!

**Comment by sampsyo** [comment]
Hmm, that's odd. The call to `proc.kill` there is guarded by an `if` that checks that the process is still running… this could use some more investigation, and I don't currently have a Windows machine set up to run WSL. We could consider just handling and ignoring the exception, but I'm concerned something subtler is going on and we'll leak the subprocess that way.

Any Windows-running volunteers available to look a little closer?

**Comment by viggyfresh** [comment]
I can poke around, although my knowledge of WSL and audioread are very limited. What am I looking for?

**Comment by sampsyo** [comment]
Good question. The main thing is that, in a line indicated in your traceback, we're calling `self.proc.kill` to terminate the `ffmpeg` process. That happens when you close the file before reading the whole thing—and after we check that the process is, in fact, still running. So the investigation to be done is to check *when* the process died, and why our [`self.proc.returncode is None`](https://github.com/beetbox/audioread/blob/fa0551cecde78f78a6face2b016217d9e66f3371/audioread/ffdec.py#L262) check is indicating that the process is still running.

**Comment by bgiesing** [comment]
Same here on OpenSUSE Leap on Windows 10 WSL using [drensin/Remixatron](https://github.com/drensin/Remixatron)
```
Traceback (most recent call last):
  File "infinite_jukebox.py", line 222, in <module>
    progress_callback=MyCallback, async=False)
  File "/mnt/c/Users/me/Desktop/Remixatron-master/Remixatron.py", line 160, in __init__
    self.__process_audio()
  File "/mnt/c/Users/me/Desktop/Remixatron-master/Remixatron.py", line 183, in __process_audio
    y, sr = librosa.core.load(self.__filename, mono=False, sr=None)
  File "/home/bgiesing/.local/lib/python2.7/site-packages/librosa/core/audio.py", line 144, in load
    y.append(frame)
  File "/home/bgiesing/.local/lib/python2.7/site-packages/audioread/ffdec.py", line 279, in __exit__
    self.close()
  File "/home/bgiesing/.local/lib/python2.7/site-packages/audioread/ffdec.py", line 263, in close
    self.proc.kill()
  File "/usr/lib64/python2.7/subprocess.py", line 1253, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/lib64/python2.7/subprocess.py", line 1243, in send_signal
    os.kill(self.pid, sig)
OSError: [Errno 3] No such process
Exception OSError: (3, 'No such process') in <bound method FFmpegAudioFile.__del__ of <audioread.ffdec.FFmpegAudioFile object at 0x7fa01e0b99d0>> ignored
```

**Comment by sampsyo** [comment]
Very strange. If you can nail down what's happening, it would be very helpful!

**Comment by bgiesing** [comment]
I have 0 knowledge of python so IDK how to help
