### ISSUE TITLE
Jupyter notebook audioread.nobackend error

### ISSUE THREAD

**Issue by nathneel** [beetbox/audioread#69]
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\process_executor.py", line 398, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\_parallel_backends.py", line 561, in __call__
    return self.func(*args, **kwargs)
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py", line 224, in __call__
    for func, args, kwargs in self.items]
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py", line 224, in <listcomp>
    for func, args, kwargs in self.items]
  File "<timed exec>", line 6, in save_folds
  File "<ipython-input-12-be5fe47a6f6e>", line 15, in extract_features
  File "<ipython-input-11-78f52d60a917>", line 4, in read_audio
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\librosa\core\audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Users\neel.nath\AppData\Local\Programs\Python\Python36\Lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError
"""

The above exception was the direct cause of the following exception:

NoBackendError                            Traceback (most recent call last)
<timed exec> in <module>()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py in __call__(self, iterable)
    960 
    961             with self._backend.retrieval_context():
--> 962                 self.retrieve()
    963             # Make sure that we get a last message telling us we are done
    964             elapsed_time = time.time() - self._start_time

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\parallel.py in retrieve(self)
    863             try:
    864                 if getattr(self._backend, 'supports_timeout', False):
--> 865                     self._output.extend(job.get(timeout=self.timeout))
    866                 else:
    867                     self._output.extend(job.get())

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\_parallel_backends.py in wrap_future_result(future, timeout)
    513         AsyncResults.get from multiprocessing."""
    514         try:
--> 515             return future.result(timeout=timeout)
    516         except LokyTimeoutError:
    517             raise TimeoutError()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\_base.py in result(self, timeout)
    429                 raise CancelledError()
    430             elif self._state == FINISHED:
--> 431                 return self.__get_result()
    432             else:
    433                 raise TimeoutError()

~\AppData\Local\Programs\Python\Python36\Lib\site-packages\joblib\externals\loky\_base.py in __get_result(self)
    380     def __get_result(self):
    381         if self._exception:
--> 382             raise self._exception
    383         else:
    384             return self._result

NoBackendError:

**Comment by sampsyo** [comment]
It's not particularly useful to open an issue that just consists of a stacktrace (and an unreadable one at that). You might be interested in some advice about how to file a bug:
https://www.cs.cornell.edu/~asampson/blog/bugrubric.html
