### ISSUE TITLE
audioread.NoBackendError

### ISSUE THREAD

**Issue by kunalkk308** [beetbox/audioread#85]
Traceback (most recent call last):
  File "train.py", line 196, in <module>
    train(train_A_dir = train_A_dir, train_B_dir = train_B_dir, model_dir = model_dir, model_name = model_name, random_seed = random_seed, validation_A_dir = validation_A_dir, validation_B_dir = validation_B_dir, output_dir = output_dir, tensorboard_log_dir = tensorboard_log_dir)
  File "train.py", line 32, in train
    wavs_A = load_wavs(wav_dir = train_A_dir, sr = sampling_rate)
  File "/Users/kunalkumar/preprocess.py", line 11, in load_wavs
    wav, _ = librosa.load(file_path, sr = sr, mono = True)
  File "/Users/kunalkumar/venv/lib/python3.7/site-packages/librosa/core/audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

Don't know what to do?

**Comment by sampsyo** [comment]
Neither do we, without more context. :smiley: We will need more context—here's [a guide I wrote once on how to write useful bug reports](https://www.cs.cornell.edu/~asampson/blog/bugrubric.html).

**Comment by kunalkk308** [comment]
https://github.com/leimao/Voice_Converter_CycleGAN

I am working on this project. Earlier when i was trying to work on the data set provided by them it worked fine but when i inputted my dataset it is giving this error.
Although the data is in the same format.

**Comment by dhpollack** [comment]
@kunalkk308 Have you installed any of the backends?  I had this error and then installed ffmpeg to remove it.

**Comment by nikunjvadodariya210903** [comment]
I am working in a project and i have this error . I have installed ffmpeg and changed the path in ffdec.py file but still getting this error . Please  please please help...............................


Traceback (most recent call last):
  File "C:/Users/Nikunj Vadodariya/Desktop/test.py", line 13, in <module>
    y,sr=librosa.load(audio)
  File "C:\Users\Nikunj Vadodariya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Users\Nikunj Vadodariya\AppData\Local\Programs\Python\Python36-32\lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

**Comment by kunalkk308** [comment]
@nikunjvadodariya210903  I was getting this error because my training data got corrupted. I changed the dataset with the original one and the issue got resolved.

**Comment by arcresu** [comment]
It sounds like you've worked out the original issue (corrupted data) so I'll close this. Anyone else running into this issue feel free to open a new report, but please include enough information about the files you are using and the environment you are running the code in so that others have a chance of helping you.
