### ISSUE TITLE
audioread.NoBackendError when looping folder

### ISSUE THREAD

**Issue by samisherif95** [beetbox/audioread#91]
So i have been trying to loop through a folder containing MP3 files and im using librosa in this loop to extract specific features from each mp3 file but each time i try to do that after looping through a few songs i get this error :

 `Traceback (most recent call last):
  File "/Users/samisherif/PycharmProjects/Test2/yarab.py", line 40, in <module>
    y, sr = librosa.load(songname, duration=15)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/librosa/core/audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError`

please i need help resolving this issue as soon as possible have been stuck on it for a while, Also im using MacOS if that makes a difference.

**Comment by sampsyo** [comment]
The first thing I might try is checking whether this happens on a specific file. It might not be supported by any of the backends you have.

**Comment by samisherif95** [comment]
@sampsyo i tried just placing just one item in the folder still didnt work .............. i have a feeling its the looping that causes the problem. any other ideas ? Thank you for your time

**Comment by sampsyo** [comment]
No, sorry! To get help from other people, it's super-duper important to be able to narrow down the problem to something that can be reliably reproduced on someone else's machine. Good luck!

**Comment by littlePP24** [comment]
I have the same propblem in windows 10  ,first I install ffmpeg from pip，then still get the same problem,but in linux is work. Then I downloan ffmpeg from this webside https://ffmpeg.zeranoe.com/builds/   unzip  add path to environment.  run 'ffmpeg -version' in cmd. If is ok. The problem shoud be solved
