### ISSUE TITLE
Python3.7 pip Error

### ISSUE THREAD

**Issue by gaoming95** [beetbox/audioread#96]
ERROR: Complete output from command python setup.py egg_info:
    ERROR: Download error on https://pypi.org/simple/pytest-runner/: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 -- Some packages may not be found!
    Couldn't find index page for 'pytest-runner' (maybe misspelled?)
    Download error on https://pypi.org/simple/: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。 -- Some packages may not be found!
    No local packages or working download links found for pytest-runner
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\G50003~1\AppData\Local\Temp\pip-install-q3asktfo\audioread\setup.py", line 58, in <module>
        'Programming Language :: Python :: 3.6',
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 144, in setup
        _install_setup_requires(attrs)
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\setuptools\__init__.py", line 139, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 717, in fetch_build_eggs
        replace_conflicting=True,
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 782, in resolve
        replace_conflicting=replace_conflicting
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 1065, in best_match
        return self.obtain(req, installer)
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\pkg_resources\__init__.py", line 1077, in obtain
        return installer(requirement)
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\setuptools\dist.py", line 784, in fetch_build_egg
        return cmd.easy_install(req)
      File "c:\users\g50003544\appdata\local\programs\python\python37\lib\site-packages\setuptools\command\easy_install.py", line 673, in easy_install
        raise DistutilsError(msg)
    distutils.errors.DistutilsError: Could not find suitable distribution for Requirement.parse('pytest-runner')

**Comment by gaoming95** [comment]
pip install pytest-runner

It works
