### ISSUE TITLE
audioread.exceptions.NoBackendError

### ISSUE THREAD

**Issue by kevinniland97** [beetbox/audioread#99]
Getting the above error when attempting to run a script. The script in question is from the project https://github.com/thomas-bouvier/music-genre-recognition. When attempting to train the model by running main.py, I get the following traceback: 
`
Traceback (most recent call last):
  File "main.py", line 409, in <module>
    main(args)
  File "main.py", line 80, in main
    data_x, data_y = load_data(args.debug)
  File "main.py", line 333, in load_data
    signal, sr = librosa.load(path + "/" + subdir + "/" + file)
  File "C:\Users\kevin\AnacondaPython\Lib\site-packages\librosa\core\audio.py", line 119, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "C:\Users\kevin\AnacondaPython\Lib\site-packages\audioread\__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.exceptions.NoBackendError
`

I have installed ffmpeg, as others have suggested from what I've seen online but I still get the aforementioned error. I am using Windows 10.

**Comment by sampsyo** [comment]
Sorry; there’s not much we can do to help without more details about exactly what’s going on with the invocation of this library and about your system setup. You might want to consider making sure that ffmpeg is available on the command line (i.e., your PATH environment variable includes the location where it lives).

**Comment by kevinniland97** [comment]
ffmpeg is available on the command line, I've already checked that.

**Comment by Gnishimura** [comment]
I'm getting this same NoBackendError: `NoBackendError: occurred at index 22`   See below for more details, thanks for your help!

#### Description
I am able to successfully load the same file as a whole using librosa.load(), the error only occurs when trying to load the file in chunks using offset and duration.  The section that throws the index error is neither the longest nor shortest section... I'm not sure what it is about that section that could be causing this.  

#### Steps/Code to Reproduce

```
# Grab waveforms of each audio segment 
self.shot_df['WAVEFORM'] = self.shot_df.apply(lambda x: librosa.load(path=self.file_path, offset = x.START_SEC, duration = x.SHOT_DURATION, res_type='kaiser_fast')[0], axis=1)

```
#### Expected Results
The above code was successfully loading the waveforms from other .wav files that I've been using, and as I said earlier, it worked when processing the file as 1 whole piece.  

#### Actual Results


`RuntimeError                              Traceback (most recent call last)
/databricks/python/lib/python3.7/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    132                 # Seek to the start of the target read
--> 133                 sf_desc.seek(int(offset * sr_native))
    134             if duration is not None:

/databricks/python/lib/python3.7/site-packages/soundfile.py in seek(self, frames, whence)
    772         position = _snd.sf_seek(self._file, frames, whence)
--> 773         _error_check(self._errorcode)
    774         return position

/databricks/python/lib/python3.7/site-packages/soundfile.py in _error_check(err, prefix)
   1356         err_str = _snd.sf_error_number(err)
-> 1357         raise RuntimeError(prefix + _ffi.string(err_str).decode('utf-8', 'replace'))
   1358 

RuntimeError: Internal psf_fseek() failed.

During handling of the above exception, another exception occurred:

     21     def extract_features(self):
---> 22         self.shot_df['WAVEFORM'] = self.shot_df.apply(lambda x: librosa.load(path=self.file_path, offset = x.START_SEC, duration = x.SHOT_DURATION, res_type='kaiser_fast')[0], axis=1)
     23 

/databricks/python/lib/python3.7/site-packages/librosa/core/audio.py in load(path, sr, mono, offset, duration, dtype, res_type)
    145         if isinstance(path, six.string_types):
    146             warnings.warn('PySoundFile failed. Trying audioread instead.')
--> 147             y, sr_native = __audioread_load(path, offset, duration, dtype)
    148         else:
    149             six.reraise(*sys.exc_info())

/databricks/python/lib/python3.7/site-packages/librosa/core/audio.py in __audioread_load(path, offset, duration, dtype)
    169 
    170     y = []
--> 171     with audioread.audio_open(path) as input_file:
    172         sr_native = input_file.samplerate
    173         n_channels = input_file.channels

/databricks/python/lib/python3.7/site-packages/audioread/__init__.py in audio_open(path, backends)
    114 
    115     # All backends failed!
--> 116     raise NoBackendError()

NoBackendError: occurred at index 22`

#### Versions
Linux-4.4.0-1098-aws-x86_64-with-debian-stretch-sid
Python 3.7.3 (default, Sep 17 2019, 23:27:09) 
[GCC 5.4.0 20160609]
NumPy 1.16.2
SciPy 1.2.1
librosa 0.7.1

**Comment by bum-bum-pav** [comment]
> ffmpeg is available on the command line, I've already checked that.

Did you remember the solution i am getting same error now. I am using python 3.9 and ffmpeg is available
